stages:
  - test
  - lint
  - release

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"

cache:
  key:
    files:
      - uv.lock
  paths:
    - .uv-cache

# Common initialization for all jobs
default:
  #image: ghcr.io/astral-sh/uv:debian-slim
  before_script:
    - uv python install $PYTHON_VERSION

# Linting (Ruff normally only needs one python version)
lint-ruff:
  stage: lint
  variables:
    PYTHON_VERSION: "3.12"
  script:
    - uv run ruff check src

# Testing with matrix for 3.11 to 3.13
pytest:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11", "3.12", "3.13"]
  script:
    - uv run --python $PYTHON_VERSION pytest



# Nightly matrix: force fresh environments and dependency upgrades
# Running nighly test asures that the latest dependencies are installed
# and do not break the tests
nightly-pytest:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11", "3.12", "3.13"]
  script:
    - echo "uv environment version"
    - uv --version
    - echo "Forcing fresh install and upgraded dependencies"
    - rm -rf .venv
    - uv cache clean
    - uv sync --python $PYTHON_VERSION --upgrade
    - echo "Using python version:"
    - uv run --python $PYTHON_VERSION python --version
    - echo "Running tests with uv"
    - uv run --python $PYTHON_VERSION pytest tests


publish-to-pypi:
  stage: release
  #image: ghcr.io/astral-sh/uv:latest 
  steps:
      - name: Install git
        run: |
          
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
  script:
    # 1. extract version from pyproject.toml 
    - VERSION=$(uv pip compile pyproject.toml --quiet | grep -oP '(?<=#  ).*(?==)' || awk -F ' = ' '/^version = / {gsub(/"/, "", $2); print $2; exit}' pyproject.toml)
    - TAG="v${VERSION}"
    - echo "Target Version: ${TAG}"

    # 2. Install git
    - apt-get update
    - apt-get install -y --no-install-recommends git

    # 3. Build & Publish
    - uv build
    - uv publish --token "${PYPI_TOKEN}"

    # 4. Create a Git Tag (Optional, but good for history)
    - |
      if [ -n "${GIT_PUSH_TOKEN}" ]; then
        git config user.email "ci@gitlab"
        git config user.name "GitLab CI"
        PUSH_URL="https://oauth2:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
        git tag "${TAG}"
        git push "${PUSH_URL}" "${TAG}" || echo "Tag already exists on remote"
      fi