curl -o xml.xsd                                 https://schema.datacite.org/meta/kernel-4/include/xml.xsd
curl -o datacite-titleType-v4.xsd               https://schema.datacite.org/meta/kernel-4/include/datacite-titleType-v4.xsd              
curl -o datacite-contributorType-v4.xsd         https://schema.datacite.org/meta/kernel-4/include/datacite-contributorType-v4.xsd
curl -o datacite-dateType-v4.xsd                https://schema.datacite.org/meta/kernel-4/include/datacite-dateType-v4.xsd
curl -o datacite-resourceType-v4.xsd            https://schema.datacite.org/meta/kernel-4/include/datacite-resourceType-v4.xsd
curl -o datacite-relationType-v4.xsd            https://schema.datacite.org/meta/kernel-4/include/datacite-relationType-v4.xsd
curl -o datacite-relatedIdentifierType-v4.xsd   https://schema.datacite.org/meta/kernel-4/include/datacite-relatedIdentifierType-v4.xsd
curl -o datacite-funderIdentifierType-v4.xsd    https://schema.datacite.org/meta/kernel-4/include/datacite-funderIdentifierType-v4.xsd
curl -o datacite-descriptionType-v4.xsd         https://schema.datacite.org/meta/kernel-4/include/datacite-descriptionType-v4.xsd
curl -o datacite-nameType-v4.xsd                https://schema.datacite.org/meta/kernel-4/include/datacite-nameType-v4.xsd
curl -o datacite-numberType-v4.xsd              https://schema.datacite.org/meta/kernel-4/include/datacite-numberType-v4.xsd             
